version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: lumen-hexagonal-microservice-mailhog
      ports:
        - "8081:8025"
        - "1025:1025"

    redis:
      image: redis:alpine
      container_name: lumen-hexagonal-microservice-redis

    mysql:
      image: mysql
      restart: always
      container_name: lumen-hexagonal-microservice-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=microservice
        - MYSQL_USER=microservice
        - MYSQL_PASSWORD=microservice
      ports:
        - "8082:3306"

    adminer:
      image: adminer
      restart: always
      ports:
        - 8089:8080

    elasticsearch:
      image: elasticsearch:5.4-alpine
      container_name: lumen-hexagonal-microservice-elasticsearch
      command: "elasticsearch -Des.cluster.name='graylog'"

    mongo:
      image: "mongo:3"
      container_name: lumen-hexagonal-microservice-mongo

    webserver:
      image: nginx:alpine
      container_name: lumen-hexagonal-microservice-webserver
      working_dir: /application
      volumes:
          - ../../:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      links:
        - graylog

    php-fpm:
      build: docker/php-fpm
      container_name: lumen-hexagonal-microservice-php-fpm
      working_dir: /application
      volumes:
        - ../../:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      links:
        - graylog

    graylog:
      image: graylog/graylog:2.4.0-1
      environment:
        # CHANGE ME!
        - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
        # Password: admin
        - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      links:
        - mongo
        - elasticsearch
      depends_on:
        - mongo
        - elasticsearch
      ports:
        # Graylog web interface and REST API
        - 9000:9000
        # Syslog TCP
        - 514:514
        # Syslog UDP
        - 514:514/udp
        # GELF TCP
        - 12201:12201
        # GELF UDP
        - 12201:12201/udp